<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" />

		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="NUnit" />
		<PackageReference Include="Microsoft.Extensions.Configuration" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" />
		<PackageReference Include="NUnit.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="NUnit3TestAdapter" />
		<PackageReference Include="Selenium.Support" />
		<PackageReference Include="Selenium.WebDriver" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Selenium.BaseComponents\Selenium.BaseComponents.csproj" />
	</ItemGroup>

</Project>
